# Generated by Django 5.2.1 on 2025-05-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0004_remove_produto_site_produto_categoria_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adiministrador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("RE", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("senha", models.CharField(max_length=100)),
            ],
        ),
    ]
