# Generated by Django 5.2.1 on 2025-06-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="re",
            field=models.CharField(
                default="temp001", max_length=20, unique=True, verbose_name="RE"
            ),
            preserve_default=False,
        ),
    ]
